import { Vehicle, Route } from "@/types/vehicle";

export const mockFleet: Vehicle[] = [
  {
    id: "toyota-camry",
    slug: "toyota-camry",
    name: "Toyota Camry",
    type: "Executive Sedan",
    nameAr: "تويوتا كامري",
    typeAr: "سيدان تنفيذية",
    passengers: 4,
    luggage: 3,
    luxuryLevel: 3,
    airportTransfer: true,
    umrahTransfer: false,
    intercityTravel: true,
    vipService: false,
    basePrice: 150,
    image: "/fleet/camry.png",
    gallery: [
      "/fleet/camry.png",
    ],
    features: ["Executive Comfort", "Air Conditioning", "Professional Driver", "Airport Pickup", "Fixed Pricing"],
    featuresAr: ["راحة تنفيذية", "تكييف هواء", "سائق محترف", "استقبال من المطار", "أسعار ثابتة"],
    description: "Executive Sedan perfect for airport transfers, couples, solo travelers, and business travelers.",
    descriptionAr: "سيارة سيدان تنفيذية مثالية لتنقلات المطار، الأزواج، المسافرين بمفردهم، ورجال الأعمال.",
    targetAudience: ["Airport Transfers", "Couples", "Solo Travelers", "Business Travelers"],
  },
  {
    id: "kia-k5",
    slug: "kia-k5",
    name: "Kia K5",
    type: "Executive Sedan",
    nameAr: "كيا K5",
    typeAr: "سيدان تنفيذية",
    passengers: 4,
    luggage: 3,
    luxuryLevel: 3,
    airportTransfer: true,
    umrahTransfer: false,
    intercityTravel: true,
    vipService: false,
    basePrice: 150,
    image: "/fleet/kia-k5.png",
    gallery: [
      "/fleet/kia-k5.png",
    ],
    features: ["Modern Design", "Air Conditioning", "Professional Driver", "Comfortable Seating", "Fixed Pricing"],
    featuresAr: ["تصميم عصري", "تكييف هواء", "سائق محترف", "مقاعد مريحة", "أسعار ثابتة"],
    description: "Modern Executive Sedan providing a smooth and stylish journey for business and leisure.",
    descriptionAr: "سيارة سيدان تنفيذية حديثة توفر رحلة سلسة وأنيقة للعمل والترفيه.",
    targetAudience: ["Airport Transfers", "Couples", "Solo Travelers", "Business Travelers"],
  },
  {
    id: "mitsubishi-xpander",
    slug: "mitsubishi-xpander",
    name: "Mitsubishi Xpander",
    type: "Family MPV",
    nameAr: "ميتسوبيشي إكسباندر",
    typeAr: "سيارة عائلية MPV",
    passengers: 7,
    luggage: 4,
    luxuryLevel: 3,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: false,
    basePrice: 250,
    image: "/fleet/mitsubishi-xpander.png",
    gallery: [
      "/fleet/mitsubishi-xpander.png",
    ],
    features: ["Spacious Cabin", "Flexible Seating", "Air Conditioning", "Family-Friendly"],
    featuresAr: ["مقصورة واسعة", "مقاعد مرنة", "تكييف هواء", "صديقة للعائلة"],
    description: "Family MPV ideal for small families and Umrah groups requiring extra space.",
    descriptionAr: "سيارة عائلية MPV مثالية للعائلات الصغيرة ومجموعات العمرة التي تحتاج إلى مساحة إضافية.",
    targetAudience: ["Small Families", "Umrah Groups", "Hotel Transfers"],
  },
  {
    id: "hyundai-staria",
    slug: "hyundai-staria",
    name: "Hyundai Staria",
    type: "Executive Van",
    nameAr: "هيونداي ستاريا",
    typeAr: "فان تنفيذي",
    passengers: 7,
    luggage: 6,
    luxuryLevel: 4,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: true,
    basePrice: 400,
    image: "/fleet/staria.png",
    gallery: [
      "/fleet/staria.png"
    ],
    features: ["VIP Interior", "Premium Seating", "Large Cargo Space", "Air Conditioning", "Wi-Fi Available"],
    featuresAr: ["تصميم داخلي VIP", "مقاعد فاخرة", "مساحة تخزين كبيرة", "تكييف هواء", "واي فاي متاح"],
    description: "Premium Executive Van ideal for VIP families and premium Umrah clients seeking maximum space and comfort.",
    descriptionAr: "فان تنفيذي فاخر مثالي لعائلات كبار الشخصيات ومعتمري الدرجة الأولى الباحثين عن أقصى درجات المساحة والراحة.",
    targetAudience: ["Families", "Large Groups", "Premium Umrah Clients", "Airport Transfers"],
  },
  {
    id: "hyundai-starex",
    slug: "hyundai-starex",
    name: "Hyundai Starex",
    type: "Executive Van",
    nameAr: "هيونداي ستاريكس",
    typeAr: "فان تنفيذي",
    passengers: 9,
    luggage: 7,
    luxuryLevel: 3,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: false,
    basePrice: 350,
    image: "/fleet/hyundai-starex.png",
    gallery: [
      "/fleet/hyundai-starex.png"
    ],
    features: ["Group Comfort", "Ample Luggage Space", "Air Conditioning", "Reliable Performance"],
    featuresAr: ["راحة جماعية", "مساحة أمتعة واسعة", "تكييف هواء", "أداء موثوق"],
    description: "Reliable Executive Van providing comfortable transport for medium groups and families.",
    descriptionAr: "فان تنفيذي موثوق يوفر نقلاً مريحاً للمجموعات المتوسطة والعائلات.",
    targetAudience: ["Families", "Large Groups", "Umrah Pilgrims", "Intercity Travel"],
  },
  {
    id: "toyota-hiace",
    slug: "toyota-hiace",
    name: "Toyota Hiace",
    type: "Executive Van",
    nameAr: "تويوتا هايس",
    typeAr: "فان تنفيذي",
    passengers: 13,
    luggage: 10,
    luxuryLevel: 3,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: false,
    basePrice: 450,
    image: "/fleet/toyota-hiace.png",
    gallery: [
      "/fleet/toyota-hiace.png"
    ],
    features: ["Maximum Capacity", "Air Conditioning", "Professional Driver", "Spacious Interior"],
    featuresAr: ["سعة قصوى", "تكييف هواء", "سائق محترف", "مقصورة واسعة"],
    description: "Spacious Executive Van perfectly suited for large Umrah groups and extensive family travel.",
    descriptionAr: "فان تنفيذي واسع ومناسب تماماً لمجموعات العمرة الكبيرة والسفر العائلي الشامل.",
    targetAudience: ["Large Groups", "Umrah Pilgrims", "Airport Transfers", "Intercity Travel"],
  },
  {
    id: "gmc-yukon",
    slug: "gmc-yukon",
    name: "GMC Yukon",
    type: "Premium SUV",
    nameAr: "جمس يوكن",
    typeAr: "سيارة دفع رباعي فاخرة",
    passengers: 7,
    luggage: 6,
    luxuryLevel: 4,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: true,
    basePrice: 500,
    image: "/fleet/gmc.png",
    gallery: [
      "/fleet/gmc.png",
    ],
    features: ["Spacious Cabin", "VIP Service", "Air Conditioning", "Premium Comfort"],
    featuresAr: ["مقصورة واسعة", "خدمة كبار الشخصيات", "تكييف هواء", "راحة فاخرة"],
    description: "Premium SUV offering a commanding presence and luxurious comfort for VIP clients.",
    descriptionAr: "سيارة دفع رباعي فاخرة توفر حضوراً قوياً وراحة فاخرة لعملاء كبار الشخصيات.",
    targetAudience: ["VIP Clients", "Corporate Executives", "Luxury Transfers", "Private Chauffeur Service"],
  }
];

export const mockRoutes: Route[] = [
  {
    id: "jeddah-makkah",
    slug: "jeddah-makkah",
    origin: "Jeddah Airport",
    destination: "Makkah",
    originAr: "مطار جدة",
    destinationAr: "مكة المكرمة",
    distance: "100 km",
    duration: "1h 15m",
    startingPrice: 200,
    image: "/hero-luxury.webp"
  },
  {
    id: "makkah-madinah",
    slug: "makkah-madinah",
    origin: "Makkah",
    destination: "Madinah",
    originAr: "مكة المكرمة",
    destinationAr: "المدينة المنورة",
    distance: "450 km",
    duration: "4h 30m",
    startingPrice: 700,
    image: "/routes/makkah-premium.webp"
  },
  {
    id: "madinah-jeddah",
    slug: "madinah-jeddah",
    origin: "Madinah",
    destination: "Jeddah Airport",
    originAr: "المدينة المنورة",
    destinationAr: "مطار جدة",
    distance: "420 km",
    duration: "4h 10m",
    startingPrice: 650,
    image: "/hero-luxury.webp"
  }
];
