import { Vehicle, Route } from "@/types/vehicle";

export const mockFleet: Vehicle[] = [
  {
    id: "toyota-camry",
    slug: "toyota-camry",
    name: "Toyota Camry",
    type: "Executive Sedan",
    nameAr: "تويوتا كامري",
    typeAr: "سيدان تنفيذية",
    passengers: 4,
    luggage: 3,
    luxuryLevel: 3,
    airportTransfer: true,
    umrahTransfer: false,
    intercityTravel: true,
    vipService: false,
    basePrice: 150,
    image: "/fleet/camry.png",
    gallery: ["/fleet/camry.png"],
    features: ["Private Transfer", "Air Conditioning", "Professional Driver", "Airport Pickup", "Fixed Pricing"],
    featuresAr: ["تنقل خاص", "تكييف هواء", "سائق محترف", "استقبال من المطار", "تسعيرة ثابتة"],
    description: "Private sedan for solo travelers, couples, and business guests. Ideal for airport transfers, hotel pickups, and intercity travel between Makkah, Madinah, and Jeddah.",
    descriptionAr: "سيدان خاص للمسافرين الفرديين والأزواج وضيوف الأعمال. مثالي لتوصيل المطار، واستقبال الفندق، والسفر بين مكة والمدينة وجدة.",
    targetAudience: ["Airport Transfers", "Couples", "Solo Travelers", "Business Travelers"],
  },
  {
    id: "hyundai-staria",
    slug: "hyundai-staria",
    name: "Hyundai Staria",
    type: "Executive Van",
    nameAr: "هيونداي ستاريا",
    typeAr: "فان تنفيذي",
    passengers: 7,
    luggage: 6,
    luxuryLevel: 4,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: true,
    basePrice: 400,
    image: "/fleet/staria.png",
    gallery: ["/fleet/staria.png"],
    features: ["7 Passengers", "Generous Luggage Space", "Private Transfer", "Air Conditioning", "Wi-Fi Available"],
    featuresAr: ["7 ركاب", "مساحة أمتعة واسعة", "تنقل خاص", "تكييف هواء", "واي فاي متاح"],
    description: "Family executive van for families and small groups. Generous space and luggage capacity — ideal for Umrah pilgrims, hotel transfers, and Ziyarah tours.",
    descriptionAr: "فان عائلي تنفيذي للعائلات والمجموعات الصغيرة. مساحة واسعة — مثالي لمعتمري العمرة وتوصيل الفنادق وجولات الزيارة.",
    targetAudience: ["Families", "Large Groups", "Premium Umrah Clients", "Airport Transfers"],
  },
  {
    id: "hyundai-h1",
    slug: "hyundai-h1",
    name: "Hyundai H1",
    type: "Executive Van",
    nameAr: "هيونداي H1",
    typeAr: "فان تنفيذي",
    passengers: 7,
    luggage: 6,
    luxuryLevel: 3,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: false,
    basePrice: 250,
    image: "/fleet/starex.png",
    gallery: ["/fleet/starex.png"],
    features: ["7 Passengers", "Ample Luggage Space", "Air Conditioning", "Reliable Performance", "Private Transfer"],
    featuresAr: ["7 ركاب", "مساحة أمتعة واسعة", "تكييف هواء", "أداء موثوق", "تنقل خاص"],
    description: "Reliable 7-seat van for medium-sized groups and families requiring comfortable airport and intercity transportation across Saudi Arabia.",
    descriptionAr: "فان موثوق ب 7 مقاعد للمجموعات المتوسطة والعائلات التي تحتاج إلى توصيل مريح بين المطار والمدن.",
    targetAudience: ["Families", "Medium Groups", "Umrah Pilgrims", "Intercity Travel"],
  },
  {
    id: "toyota-hiace",
    slug: "toyota-hiace",
    name: "Toyota Hiace",
    type: "Large Van",
    nameAr: "تويوتا هايس",
    typeAr: "فان كبير",
    passengers: 13,
    luggage: 10,
    luxuryLevel: 3,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: false,
    basePrice: 350,
    image: "/fleet/hiace.png",
    gallery: ["/fleet/hiace.png"],
    features: ["13 Passengers", "Air Conditioning", "Professional Driver", "Spacious Interior", "Group Booking"],
    featuresAr: ["13 راكب", "تكييف هواء", "سائق محترف", "مقصورة واسعة", "حجز مجموعات"],
    description: "Spacious 13-seat van for large families and Umrah groups. Serves airport transfers, hotel drop-offs, and intercity travel for groups requiring dependable transportation.",
    descriptionAr: "فان واسع ب 13 مقعداً للعائلات الكبيرة ومجموعات العمرة. يخدم توصيل المطار والفندق والسفر بين المدن.",
    targetAudience: ["Large Groups", "Umrah Pilgrims", "Airport Transfers", "Intercity Travel"],
  },
  {
    id: "coaster-bus",
    slug: "coaster-bus",
    name: "Coaster Bus",
    type: "Minibus",
    nameAr: "حافلة كوستر",
    typeAr: "حافلة صغيرة",
    passengers: 22,
    luggage: 20,
    luxuryLevel: 3,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: false,
    basePrice: 500,
    image: "/fleet/coaster.png",
    gallery: ["/fleet/coaster.png"],
    features: ["22 Passengers", "Air Conditioning", "Overhead Storage", "PA System", "Group Booking"],
    featuresAr: ["22 راكب", "تكييف هواء", "تخزين علوي", "نظام صوتي", "حجز مجموعات"],
    description: "22-seat minibus for large pilgrim groups and tour groups. Ideal for coordinated group transportation between airports, hotels, and cities across Saudi Arabia.",
    descriptionAr: "حافلة صغيرة ب 22 مقعداً لمجموعات الحجاج والسياح. مثالية للنقل الجماعي بين المطارات والفنادق والمدن.",
    targetAudience: ["Very Large Groups", "Tour Groups", "Pilgrimage Groups", "Corporate Events"],
  },
  {
    id: "gmc-denali",
    slug: "gmc-denali",
    name: "GMC Denali",
    type: "Premium SUV",
    nameAr: "جمس دينالي",
    typeAr: "سيارة دفع رباعي فاخرة",
    passengers: 7,
    luggage: 6,
    luxuryLevel: 5,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: true,
    basePrice: 450,
    image: "/fleet/gmc.png",
    gallery: ["/fleet/gmc.png"],
    features: ["7 Passengers", "Spacious Cabin", "Air Conditioning", "VIP Service", "Private Transfer"],
    featuresAr: ["7 ركاب", "مقصورة واسعة", "تكييف هواء", "خدمة كبار الشخصيات", "تنقل خاص"],
    description: "Premium 7-seat SUV for VIP clients, corporate executives, and travelers requiring a commanding and comfortable private vehicle for airport transfers and intercity travel.",
    descriptionAr: "دفع رباعي فاخر ب 7 مقاعد لعملاء كبار الشخصيات والمسؤولين التنفيذيين والمسافرين الباحثين عن سيارة خاصة مريحة لتوصيل المطار والسفر بين المدن.",
    targetAudience: ["VIP Clients", "Corporate Executives", "Luxury Transfers", "Private Chauffeur Service"],
  }
];

export const mockRoutes: Route[] = [
  {
    id: "jeddah-makkah",
    slug: "jeddah-makkah",
    origin: "Jeddah Airport",
    destination: "Makkah",
    originAr: "مطار جدة",
    destinationAr: "مكة المكرمة",
    distance: "100 km",
    duration: "1h 15m",
    startingPrice: 200,
    image: "/hero-luxury.webp"
  },
  {
    id: "makkah-madinah",
    slug: "makkah-madinah",
    origin: "Makkah",
    destination: "Madinah",
    originAr: "مكة المكرمة",
    destinationAr: "المدينة المنورة",
    distance: "450 km",
    duration: "4h 30m",
    startingPrice: 700,
    image: "/routes/makkah-premium.webp"
  },
  {
    id: "madinah-jeddah",
    slug: "madinah-jeddah",
    origin: "Madinah",
    destination: "Jeddah Airport",
    originAr: "المدينة المنورة",
    destinationAr: "مطار جدة",
    distance: "420 km",
    duration: "4h 10m",
    startingPrice: 650,
    image: "/hero-luxury.webp"
  }
];
