import { Vehicle, Route } from "@/types/vehicle";

export const mockFleet: Vehicle[] = [
  {
    id: "toyota-camry",
    slug: "toyota-camry",
    name: "Toyota Camry",
    type: "Executive Sedan",
    nameAr: "تويوتا كامري",
    typeAr: "سيدان تنفيذية",
    passengers: 4,
    luggage: 3,
    luxuryLevel: 3,
    airportTransfer: true,
    umrahTransfer: false,
    intercityTravel: true,
    vipService: false,
    basePrice: 150,
    image: "/fleet/camry.png",
    gallery: [
      "/fleet/camry.png",
      "/fleet/camry-interior.png",
      "/fleet/camry-trunk.png"
    ],
    features: ["Executive Comfort", "Air Conditioning", "Professional Driver", "Airport Pickup", "Fixed Pricing"],
    featuresAr: ["راحة تنفيذية", "تكييف هواء", "سائق محترف", "استقبال من المطار", "أسعار ثابتة"],
    description: "Executive Sedan perfect for airport transfers, couples, solo travelers, and business travelers.",
    descriptionAr: "سيارة سيدان تنفيذية مثالية لتنقلات المطار، الأزواج، المسافرين بمفردهم، ورجال الأعمال.",
    targetAudience: ["Airport Transfers", "Couples", "Solo Travelers", "Business Travelers"],
  },
  {
    id: "gmc-yukon",
    slug: "gmc-yukon",
    name: "GMC Yukon",
    type: "Luxury SUV",
    nameAr: "جمس يوكن",
    typeAr: "سيارة دفع رباعي فاخرة",
    passengers: 7,
    luggage: 6,
    luxuryLevel: 4,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: false,
    basePrice: 500,
    image: "/fleet/gmc.png",
    gallery: [
      "/fleet/gmc.png",
      "/fleet/yukon-interior.png",
      "/fleet/yukon-trunk.png"
    ],
    features: ["Spacious Cabin", "Comfortable Seating", "Family-Friendly"],
    featuresAr: ["مقصورة واسعة", "مقاعد مريحة", "صديقة للعائلة"],
    description: "Spacious Family MPV designed for small groups and Umrah travelers ensuring comfort and reliability.",
    descriptionAr: "سيارة عائلية واسعة مصممة للمجموعات الصغيرة ومعتمري بيت الله الحرام لضمان الراحة والموثوقية.",
    targetAudience: ["Families", "Small Groups", "Umrah Travelers"],
  },
  {
    id: "hyundai-staria",
    slug: "hyundai-staria",
    name: "Hyundai Staria",
    type: "Premium Luxury Family Van",
    nameAr: "هيونداي ستاريا",
    typeAr: "فان عائلي فاخر",
    passengers: 7,
    luggage: 6,
    luxuryLevel: 4,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: true,
    basePrice: 400,
    image: "/fleet/staria.png",
    gallery: [
      "/fleet/staria.png"
    ],
    features: ["VIP Interior", "Premium Seating", "Large Cargo Space"],
    featuresAr: ["تصميم داخلي VIP", "مقاعد فاخرة", "مساحة تخزين كبيرة"],
    description: "Premium Luxury Family Van ideal for VIP families and premium Umrah clients seeking maximum space and comfort.",
    descriptionAr: "فان عائلي فاخر مثالي لعائلات كبار الشخصيات ومعتمري الدرجة الأولى الباحثين عن أقصى درجات المساحة والراحة.",
    targetAudience: ["Families", "Premium Umrah Clients"],
  },
  {
    id: "ford-taurus",
    slug: "ford-taurus",
    name: "Ford Taurus",
    type: "Premium Sedan",
    nameAr: "فورد تورس",
    typeAr: "سيدان فاخرة",
    passengers: 4,
    luggage: 3,
    luxuryLevel: 4,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: false,
    basePrice: 350,
    image: "/fleet/taurus.png",
    gallery: [
      "/fleet/taurus.png",
      "/fleet/taurus-interior.png",
      "/fleet/taurus-trunk.png"
    ],
    features: ["Comfortable Ride", "Quiet Cabin", "Premium Experience"],
    featuresAr: ["رحلة مريحة", "مقصورة هادئة", "تجربة فاخرة"],
    description: "Premium Sedan accommodating up to 4 passengers, perfect for business travelers, couples, and small families.",
    descriptionAr: "سيارة سيدان فاخرة تتسع لما يصل إلى 4 ركاب، مثالية لرجال الأعمال، والأزواج، والعائلات الصغيرة.",
    targetAudience: ["Business Travelers", "Couples", "Small Families"],
  },
  {
    id: "toyota-coaster",
    slug: "toyota-coaster",
    name: "Toyota Coaster",
    type: "Mini Coach",
    nameAr: "تويوتا كوستر",
    typeAr: "حافلة صغيرة",
    passengers: 25,
    luggage: 15,
    luxuryLevel: 2,
    airportTransfer: true,
    umrahTransfer: true,
    intercityTravel: true,
    vipService: false,
    basePrice: 700,
    image: "/fleet/coaster.png",
    gallery: [
      "/fleet/coaster.png"
    ],
    features: ["Group Comfort", "Professional Tour Transportation", "Long Distance Travel"],
    featuresAr: ["راحة جماعية", "نقل سياحي محترف", "سفر لمسافات طويلة"],
    description: "Mini Coach designed for medium to large Umrah groups and corporate events, offering group comfort and professional transport.",
    descriptionAr: "حافلة صغيرة مصممة لمجموعات العمرة المتوسطة إلى الكبيرة والفعاليات التجارية، وتوفر راحة جماعية ونقلاً احترافياً.",
    targetAudience: ["Umrah Groups", "Corporate Groups", "Travel Agencies"]
  }
];

export const mockRoutes: Route[] = [
  {
    id: "jeddah-makkah",
    slug: "jeddah-makkah",
    origin: "Jeddah Airport",
    destination: "Makkah",
    originAr: "مطار جدة",
    destinationAr: "مكة المكرمة",
    distance: "100 km",
    duration: "1h 15m",
    startingPrice: 200,
    image: "/hero-luxury.webp"
  },
  {
    id: "makkah-madinah",
    slug: "makkah-madinah",
    origin: "Makkah",
    destination: "Madinah",
    originAr: "مكة المكرمة",
    destinationAr: "المدينة المنورة",
    distance: "450 km",
    duration: "4h 30m",
    startingPrice: 700,
    image: "/routes/makkah-premium.webp"
  },
  {
    id: "madinah-jeddah",
    slug: "madinah-jeddah",
    origin: "Madinah",
    destination: "Jeddah Airport",
    originAr: "المدينة المنورة",
    destinationAr: "مطار جدة",
    distance: "420 km",
    duration: "4h 10m",
    startingPrice: 650,
    image: "/hero-luxury.webp"
  }
];
